GET http://localhost:3000/users

####

GET http://localhost:3000/users/blinky

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "blinky",
    "password": 123456,
    "name": "Miguel"
}

###

DELETE http://localhost:3000/users/a

###

PATCH http://localhost:3000/users/blinky
Content-Type: application/json 

{
  "username": "blinko"
}